name: snsmc
version: 0.0.1-SNAPSHOT
description: The snsmc plugin
author: yuxuanchiadm
depend: [ProtocolLib]

main: org.snsmc.Main

commands:
  snsmc:
    description: SNSMC command.
    usage: /<snsmc> [args...]
    permission: snsmc.admin
    permission-message: You do not have permission to manage SNSMC plugin

permissions:
  snsmc.admin:
    default: op
